export const ActionTypes = {
	TXT_INT_ADD_CATEGORIA: 'TXT_INT_ADD_CATEGORIA',
	TXT_INT_ADD_AMBITO: 'TXT_INT_ADD_AMBITO',
	TXT_INT_ADD_ESTILO: 'TXT_INT_ADD_ESTILO',
	TXT_INT_ADD_COLOR: 'TXT_INT_ADD_COLOR',
	TXT_INT_ADD_FUENTE: 'TXT_INT_ADD_FUENTE',
	UI_PROGRESS: 'UI_PROGRESS',
};
